version: "3.2"

services:
  ts-bp:
    build:
      context: .
      dockerfile: dev/docker/Dockerfile
    command: npm run watch
    ports:
      - "3001:3001"
    networks:
      - ts-bp-net
    volumes:
      - .:/var/app/ts-bp-be
      - /var/app/ts-bp-be/node_modules
    env_file:
      - .env # it will overwrite .env file content
    depends_on:
      - ts-bp_postgres

networks:
  ts-bp-net:
    driver: bridge
